[options]
db_host = localhost
db_port = 5432
db_user = admin
db_password = 1234
default_productivity_apps = True
addons_path = /Users/psanyaja/Workspace/Odoo/odoo-16/odoo/addons,/Users/psanyaja/Workspace/Odoo/odoo-16/addons,/Users/psanyaja/Workspace/Odoo/odoo-16/dev-addons
admin_passwd = $pbkdf2-sha512$25000$KeVcK.X8v7cWopRy7l1LKQ$BZoe0zsCoxtJAtuCnZJ4q4LLF/Q/c1nMgQO5UtPrSeRjJw.nAQ32OVroDRNybs2IUgmhXe1VNq8CNq8K6i5teQ

